import torch
from ddpm.sample import sample_ddim

@torch.no_grad()
def eval_with_cur_model(cur_model, rm, alphas_cumprod, device, ddim_steps=200, eta=0.5, n_eval=8):
    # Get rewards of the image generated by cur_model.
    cur_model.eval()
    x0, _ = sample_ddim(model=cur_model, shape=(n_eval,3,64,64), alphas_cumprod=alphas_cumprod,
                        device=device, ddim_steps=ddim_steps, eta=eta)
    return rm(x0).mean().item()